# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.IntegerField(choices=[(0, b'De 18 a 30 a\xc3\xb1os'), (1, b'De 30 a 40 a\xc3\xb1os'), (2, b'De 40 a 50 a\xc3\xb1os'), (3, b'De 50 a 60 a\xc3\xb1os'), (4, b'De 60 a 100 a\xc3\xb1os')])),
                ('tieneCarro', models.BooleanField()),
                ('sugerencia', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyLab.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('rango', models.IntegerField(choices=[(0, b'De 18 a 30 a\xc3\xb1os'), (1, b'De 30 a 40 a\xc3\xb1os'), (2, b'De 40 a 50 a\xc3\xb1os'), (3, b'De 50 a 60 a\xc3\xb1os'), (4, b'De 60 a 100 a\xc3\xb1os')])),
                ('tieneCarro', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='prospecto',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyLab.Vendedor'),
        ),
        migrations.AddField(
            model_name='perfilvendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyLab.Vendedor'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vendedores',
            field=models.ManyToManyField(through='proyLab.PerfilVendedor', to='proyLab.Vendedor'),
        ),
    ]
